### ISSUE TITLE
How to migrate from official Drone helm charts

### ISSUE THREAD

**Issue by tolgap** [volker-raschek/drone-charts#1]
@volker-raschek Thanks so much for this.

As someone who is very new to Kubernetes, I'm not sure how I can migrate from the official helm charts to this one.
Do I need to delete everything first? Or can I just alter my values somehow to "upgrade" my current Drone installation from the official charts?

**Comment by volker-raschek** [comment]
Hi @tolgap, 
I think the first important point is which version do you have deployed inside your cluster. With the official helm chart it is possible to overwrite the image tag which should be used. 

If you want to upgrade from v1.x to v2.0, I don't know if there are some breaking changes from the development point of view. So I would probably rather advise to reinstall drone. The most config parameters can be copied from the old values.yml to the new one.

**Comment by tolgap** [comment]
Hi @volker-raschek 

Wow thanks for the pointers on overriding the `image.tag` values. I'm not sure how I missed this.

I just bumped the versions in my `drone-values.yaml` and `drone-runner-kube-values.yaml` files and ran a `helm upgrade`. I am now on the newest versions.

Thank you very much!
