### ISSUE TITLE
replicaCount unsed

### ISSUE THREAD

**Issue by pi3ch** [volker-raschek/drone-charts#11]
https://github.com/volker-raschek/drone-charts/blob/4a0ec52f1229c8dcc786f9081060464df401bc50/values.yaml#L5

Doesn't seems to be used anywhere? is this missing or similar to official drone chart the setup is singleton?

**Comment by volker-raschek** [comment]
Hi @pi3ch, 
the property is obsolete. I don't know if drone is scalable by application design or not. For this reason I removed in the deployment the replicaCount spec. If drone is scalable replicaCount make sense and should be implemented again.
