### ISSUE TITLE
Support priorityClassName

### ISSUE THREAD

**Issue by tokyowizard** [volker-raschek/drone-charts#6]
Thank you for the drone charts!

Could support for setting `spec.template.spec.priorityClassName` in the Deployment be added? I could create a pull request if you would like.

**Comment by volker-raschek** [comment]
Hi @tokyowizard, 
I released for some minutes the chart version `0.6.0` to define optionally `spec.template.spec.priorityClassName`.
 
Thanks for reporting the missing feature :)

**Comment by tokyowizard** [comment]
Thanks, @volker-raschek ! It works perfectly!
